name: release

on:
  # Support both manual tag pushes (for backward compatibility)
  push:
    tags:
      - "v*"
  # Support release-please created releases
  release:
    types: [published, created]
  # Allow manual triggering for debugging
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
          generate_attestations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}