name: release

on:
  # Support both manual tag pushes (for backward compatibility)
  push:
    tags:
      - "v*"
  # Support release-please created releases
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
          generate_attestations: true